[package]
name = "ChatApp"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.1", features = ["ws"] }
tokio = { version = "1.44.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["cors"]}

tungstenite = "0.26.2" # For websockets
futures-util = "0.3.31"